#!/bin/bash
#
xrandr \
  --output DisplayPort-0 \
  --primary \
  --mode 1920x1080 \
  --pos 1080x0 \
  --rotate normal \
  --rate 144.00 \
  --output DisplayPort-1 \
  --off \
  --output DisplayPort-2 \
  --off \
  --output HDMI-A-0 \
  --mode 1920x1080 \
  --pos 0x0 \
  --rotate left \
  --output HDMI-A-1-1 \
  --off \
  --output DisplayPort-1-3 \
  --off \
  --output DisplayPort-1-4 \
  --off \
  --output DisplayPort-1-5 \
  --off

feh --bg-fill ~/Pictures/wallpaper_2.jpg ~/Pictures/wallpaper_1.jpg

primary_monitor=$(xrandr --query | grep " connected" | grep "primary" | cut -d" " -f1)

# Startup background services

pgrep -x sxhkd >/dev/null || sxhkd &
lxsession &
xautolock -time 10 -locker '/usr/bin/slock' -detectsleep &
picom &
dunst &

# Startup one-offs

xrdb -q
setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl

# Bspwm config

bspc monitor $primary_monitor -d 1 2 3 4 5 6 7

workspace=8
for m in $(xrandr --query | grep " connected" | grep -v "primary" | cut -d" " -f1); do
  bspc monitor $m -d $workspace
  ((workspace++))
done

bspc config border_width 1
bspc config window_gap 5

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# Bspwm rules

bspc rule -a "firefox:*:Picture-in-Picture" sticky=on state=floating

STEAM_APPS=$(ls ~/.steam/steam/steamapps | grep appmanifest | sed 's/[^0-9]*//g')

for app in $STEAM_APPS; do
  bspc rule -a "steam_app_$app:*:*" desktop="7" state=fullscreen follow=on
done

# Polybar

MONITOR=$primary_monitor polybar --reload main &
for m in $(xrandr --query | grep " connected" | grep -v "primary" | cut -d" " -f1); do
  MONITOR=$m polybar --reload secondary &
done
